### ISSUE TITLE
Version incompatible with current release (0.0.4)

### ISSUE THREAD

**Issue by JayH2971** [StraDaMa/RandomizedBattleMusicMod_LC#2]
Sorry to bug you about this since I know it happened before, but both LC1 and LC2 show version compatibility errors.

![image](https://github.com/StraDaMa/RandomizedBattleMusicMod_LC/assets/37541932/d35c2113-2dda-4406-8aea-2fa58fb2ae50)

**Comment by StraDaMa** [comment]
Should work on the new game version on Release 5 now.

**Comment by JayH2971** [comment]
Thank you! I'll try it out

**Comment by JayH2971** [comment]
It loads! Looks like it works.
